name: http_either
description: A starting point for Dart libraries or applications.
version: 1.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  either_dart: ^1.0.0
  http: ^1.2.1
  logger: ^2.3.0
  retry: ^3.1.2
  # path: ^1.8.0

dev_dependencies:
  collection: ^1.18.0
  lints: ^3.0.0
  test: ^1.24.0
