name: http_either
description: is a Dart package designed to simplify HTTP request handling by integrating the capabilities of http, retry, either_dart and logger.
version: 1.1.4
repository: https://github.com/anjarnaufals/http_either

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  either_dart: ^1.0.0
  http: ^1.3.0
  logger: ^2.4.0
  retry: ^3.1.2

dev_dependencies:
  collection: ^1.19.0
  lints: ^3.0.0
  test: ^1.25.15
  frontend_server_client: ^4.0.0
